### ISSUE TITLE
SuperCollider plugin crash on Mac OS 13.2.1 M2 Max

### ISSUE THREAD

**Issue by dmartinp** [Spacechild1/vstplugin#14] opened 2023-03-02 20:30 UTC
Vienna Synchron Pianos VST3 crashes with the following error posted in SuperCollider 3.13.0

-> a VSTPluginController
WARNING: read(): EOF
WARNING: WatchDog: subprocess was terminated with signal 11 (Segmentation fault: 11)
name: Vienna Synchron Pianos
type: VST 2.4 (synth) [bridged]
path: /Library/Audio/Plug-Ins/VST/Vienna Synchron Pianos.vst
vendor: VSL
category: Synth
version: 65792
inputs: 0ch
outputs: 18ch
parameters: 2181
programs: 1
presets: 0
editor: true
MIDI input: true
MIDI output: false
WARNING: plugin 'Vienna Synchron Pianos' crashed

VSTPlugin built for arm64.

Vienna Syncrhon Pianos VST is not native to Apple M2 Max

**Comment by Spacechild1** [comment] 2023-03-04 23:38
Closing as duplicate of https://git.iem.at/pd/vstplugin/-/issues/191

**Closed by Spacechild1** 2023-03-04 23:38 UTC
