### ISSUE TITLE
Reaper plugins ...

### ISSUE THREAD

**Issue by oliverstotz** [Spacechild1/vstplugin#17] opened 2024-05-15 15:22 UTC
Hi,

although being close to perfect, [vstplugin~] still has issues with some plugins.

This time it's the "REA Plugs", which are available for free from the REAPER website, offering some very useful and handy FX.

https://www.reaper.fm/reaplugs/#

These are the issues:
1.) The plugin window is too small (and therefore hides some parameters)
2.) For a strange reason, the number of listed parameters is always limited to 12, but the plugin has much more

Applying changes to the (visible) params and saving / recalling as .fxp works, though

All of those work well and with the correct window size in other VST Hosts (Cubase, Ableton Live, Vegas etc.)

Best

Oliver

**Comment by Spacechild1** [comment] 2024-05-15 15:26
Closing as duplicate of https://git.iem.at/pd/vstplugin/-/issues/171 ;-)

Please update your original bug report to also include the parameter list issue.

**Closed by Spacechild1** 2024-05-15 15:26 UTC

**Comment by oliverstotz** [comment] 2024-05-15 15:42
Hi, 

unfortunately the issue is still there, at least on my machine (see attachment).

![reaplug_window_vstplugin_0 6](https://github.com/Spacechild1/vstplugin/assets/19552265/3946619b-8a86-4d34-8ac4-fa429413211a)


Here are my specs:

Windows 7 64, PD 0.54.1, [vstplugin~] v. 0.6

=========================================================

Plus, another obstacle prevented me from using version 0.6 until now:

My old beloved Organ instrument "LinPlug Organ 3" crashes with your new [vstplugin~] version (0.6),
not with the previous one (0.5.4) ! , which is why i didn't update so far.

Now, that alone wouldn't be too big of a deal, since LinPlug as a company stopped many years ago, and sooner or later i would have to switch to another instrument anyway, so please don't bother with this one !

**Comment by Spacechild1** [comment] 2024-05-15 16:57
> unfortunately the issue is still there, at least on my machine (see attachment).

Well, https://git.iem.at/pd/vstplugin/-/issues/171 is still open... If you encounter any other issues, please prefer the "official" issue tracker https://git.iem.at/pd/vstplugin/-/issues.
